import { Info } from "lucide-react";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { ConfidenceIndicator } from "@/components/status/confidence-indicator";
import type { DifferenceSeverity, QcResult } from "@/types/domain";

const SEVERITY_ORDER: DifferenceSeverity[] = ["critical", "important", "minor", "uncertain"];
const SEVERITY_COPY: Record<DifferenceSeverity, string> = {
  critical: "Critical",
  important: "Important",
  minor: "Minor",
  uncertain: "Uncertain",
};

function matchTone(percentage: number) {
  if (percentage >= 95) return "text-success";
  if (percentage >= 80) return "text-signal-600";
  return "text-critical";
}

export function QcSummary({
  qc,
  overallConfidence,
}: {
  qc: QcResult | undefined;
  overallConfidence: number | undefined;
}) {
  const counts = SEVERITY_ORDER.map((severity) => ({
    severity,
    count: qc?.differences.filter((d) => d.severity === severity).length ?? 0,
  }));

  return (
    <div className="space-y-4">
      <div className="flex items-start justify-between gap-3">
        <div>
          <p className="flex items-center gap-1 text-xs font-medium text-text-muted uppercase tracking-wide">
            Script match
            <Tooltip>
              <TooltipTrigger aria-label="What is script match?">
                <Info className="size-3" />
              </TooltipTrigger>
              <TooltipContent className="max-w-64 text-xs">
                Generated by comparing this recording&apos;s transcript against the approved
                recording script — not a measure of transcription confidence.
              </TooltipContent>
            </Tooltip>
          </p>
          <p className={`mt-1 text-3xl font-semibold tabular-nums ${matchTone(qc?.matchPercentage ?? 0)}`}>
            {qc ? `${qc.matchPercentage}%` : "—"}
          </p>
        </div>
        {overallConfidence !== undefined && (
          <div className="text-right">
            <p className="text-xs font-medium text-text-muted uppercase tracking-wide">
              Transcription
            </p>
            <div className="mt-1.5">
              <ConfidenceIndicator confidence={overallConfidence} />
            </div>
          </div>
        )}
      </div>

      <div className="grid grid-cols-2 gap-2">
        {counts.map(({ severity, count }) => (
          <div
            key={severity}
            className="flex items-center justify-between rounded-md border border-border-subtle px-3 py-2"
          >
            <span className="text-xs text-text-secondary">{SEVERITY_COPY[severity]}</span>
            <span className="font-mono text-sm font-medium text-ink-900">{count}</span>
          </div>
        ))}
      </div>
    </div>
  );
}
